dist: bionic
sudo: required
arch: s390x
jdk:
- openjdk11
services:
- docker
before_install:
- mkdir -vp ~/.docker/cli-plugins/
- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-s390x" > ~/.docker/cli-plugins/docker-buildx
- chmod a+x ~/.docker/cli-plugins/docker-buildx
- sudo service docker restart
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker info
- sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
sudo apt-get install -y apt-utils
sudo apt-get install -y git make cmake gcc-8 g++-8 tar wget patch ruby curl conntrack shellcheck openssl libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev libarchive-dev diffutils gzip file procps python3 perl zip
  #- sudo apt-get install linux-image-$(uname -r) socat -y
  #- sudo sysctl net.ipv6.conf.all.disable_ipv6=1
  #- sudo sysctl net.ipv6.conf.default.disable_ipv6=1
  #- sudo sysctl net.ipv6.conf.lo.disable_ipv6=1
  #- sudo sysctl -p
  #- sudo systemctl enable docker.service
  #- sudo systemctl restart docker
  #- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  #- sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  #- sudo swapoff -a 
  #- sudo apt-get install -y kubelet kubeadm kubectl
  #- sudo kubeadm reset
  #- sudo kubeadm init phase certs all
  #- sudo kubeadm init phase kubeconfig all
  #- sudo kubeadm init phase control-plane all --pod-network-cidr=10.244.0.0/16
  #- sudo kubeadm init --v=1 --skip-phases=certs,kubeconfig,control-plane --ignore-preflight-errors=all --pod-network-cidr=10.244.0.0/16
#- sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --v=5
#- mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#- sudo chown $(id -u):$(id -g) $HOME/.kube/config
#- sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#- sudo kubectl taint nodes --all node-role.kubernetes.io/master- && sudo kubectl get nodes

install:
- kubectl get pods --all-namespaces
env:
  global:
  - DOCKER_REGISTRY=docker.io
  - DOCKER_BUILD_ARGS="-q"
