dist: bionic
sudo: required
arch: s390x
services:
- docker
before_install:
- mkdir -vp ~/.docker/cli-plugins/
- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-s390x" > ~/.docker/cli-plugins/docker-buildx
- chmod a+x ~/.docker/cli-plugins/docker-buildx
- sudo service docker restart
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker info
install:
- docker info
env:
  global:
  - DOCKER_REGISTRY=docker.io
  - DOCKER_BUILD_ARGS="-q"
