FROM s390x/ubuntu:focal

ARG user=jenkins
ARG group=jenkins
ARG uid=1001
ARG gid=1002

ENV JENKINS_HOME /home/${user}

# Jenkins is run with user `jenkins`, uid = 1000
RUN groupadd -g ${gid} ${group} \
    && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}
RUN chown -R ${user}:${user} /home/${user}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update ; \
    apt-get install -y make sudo wget git docker.io shellcheck openjdk-11-jdk tar gzip zip patch ruby curl openssl diffutils file procps python3 perl || true; \
    apt-get install -y docker.io iptables ebtables ethtool ca-certificates conntrack socat git nfs-common cifs-utils apt-transport-https gnupg2 software-properties-common bridge-utils ipcalc aufs-tools kmod || true; \
    apt-get clean

# Add the jenkins user to sudoers
RUN echo "${user}    ALL=(ALL)    NOPASSWD:ALL" >> etc/sudoers

RUN wget https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-s390x; \
    mkdir -p ~/.docker/cli-plugins; \
    mv buildx-v0.6.1.linux-s390x ~/.docker/cli-plugins/docker-buildx; \
    chmod a+x ~/.docker/cli-plugins/docker-buildx

RUN wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz; \
    tar -zxf apache-maven-3.8.4-bin.tar.gz; \
    mv apache-maven-3.8.4 /opt/; \
    rm -f apache-maven-3.8.4-bin.tar.gz

VOLUME /var/lib/docker
